/license/v1/license/widevine$$crunchyroll
wv-license.sr.roku.com/license/v2/license/wv$$roku
cwip-shaka-proxy
contentlicenseservice/v1/licenses
media-license-server/validate-auth-token
wv-keyos.licensekeyserver
vcas-wv-ew.waoo.tv/
uplynk.com/wv
widevine.com/proxy
expressplay.com/hms/wv
pluto.tv/v1/wv
/licensing/
license-ap
getRawWidevineLicense
AcquireLicense
acquire-license
widevine-proxy
licenseManager.do
widevine
license
cenc
